version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
  ECartapp:
    build: .
    image: ascendappp
    container_name: "ascendapp"
    ports:
      - 9090:9090
    links: 
      - mongodb  