spring:
   application:
      name: apigateway
   cloud:
    gateway:
      discovery:
          locator:
           enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:9100"
            allowedMethods:
            - GET
            - POST  
eureka:
  instance:
       hostname: localhost
 # preferIpAddress: false 
  client:
       serviceUrl:
           defaultZone:  http://localhost:8761/eureka
server:
   port: 9900

   
jwt:
 secret : AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG
 expiration: 20400
 
auth:
  routes : /ECartPGPTen/api/ecarto/status,/auth/token
gateway:
  passroute: /ECartPGPTen/api/**,/userdashboard/api/**